columns:
  - Index: int
  - UsingIP: int
  - LongURL: int
  - ShortURL: int
  - Symbol@: int
  - Redirecting//: int
  - PrefixSuffix-: int
  - SubDomains: int
  - HTTPS: int
  - DomainRegLen: int
  - Favicon: int
  - NonStdPort: int
  - HTTPSDomainURL: int
  - RequestURL: int
  - AnchorURL: int
  - LinksInScriptTags: int
  - ServerFormHandler: int
  - InfoEmail: int
  - AbnormalURL: int
  - WebsiteForwarding: int
  - StatusBarCust: int
  - DisableRightClick: int
  - UsingPopupWindow: int
  - IframeRedirection: int
  - AgeofDomain: int
  - DNSRecording: int
  - WebsiteTraffic: int
  - PageRank: int
  - GoogleIndex: int
  - LinksPointingToPage: int
  - StatsReport: int
  - class: int


# numeric_columns:
#   - Index
#   - UsingIP
#   - LongURL
#   - ShortURL
#   - Symbol@
#   - Redirecting//
#   - PrefixSuffix-
#   - SubDomains
#   - HTTPS
#   - DomainRegLen
#   - Favicon
#   - NonStdPort
#   - HTTPSDomainURL
#   - RequestURL
#   - AnchorURL
#   - LinksInScriptTags
#   - ServerFormHandler
#   - InfoEmail
#   - AbnormalURL
#   - WebsiteForwarding
#   - StatusBarCust
#   - DisableRightClick
#   - UsingPopupWindow
#   - IframeRedirection
#   - AgeofDomain
#   - DNSRecording
#   - WebsiteTraffic
#   - PageRank
#   - GoogleIndex
#   - LinksPointingToPage
#   - StatsReport
#   - class
