

"""
      DEFINING COMMON CONSTANTS VARIABLE FOR TRAINING PIPELINE

"""
TARGET_COLUMN ="class"
PIPELINE_NAME:str ="networksecurity"
ARTIFACT_DIR:str ="Artifacts"
FILE_NAME:str ="PhisingData.csv"
TRAINE_FILE_NAME:str ="train.csv"
TEST_FILE_NAME:str ="test.csv"


"""
     DATTA INGESTION REALETD CONSTANTS 

"""
DATA_INGESTION_COLLECTION_NAME:str ="NetworkData"
DATA_INGESTION_DATABASE_NAME:str ="Ashok"
DATA_INGESTION_DIR_NAME:str ="data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR:str ="feature_store"
DATA_INGESTION_INGESTED_DIR:str ="ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO:float=0.2





